"""add proposals and approval policy

Revision ID: 078c8a67f71a
Revises: 61ce2ca7e942
Create Date: 2026-08-01 13:27:29.220057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '078c8a67f71a'
down_revision: Union[str, Sequence[str], None] = '61ce2ca7e942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('discussion_summary', sa.Text(), nullable=True),
    sa.Column('workflow', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','approved','rejected','submitted')", name='ck_proposals_status'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proposals_project_id_created_at', 'proposals', ['project_id', 'created_at'], unique=False)
    op.create_table('proposal_approvals',
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('approve','reject')", name='ck_proposal_approvals_decision'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('proposal_id', 'user_id')
    )
    op.add_column('projects', sa.Column('approval_policy', sa.String(length=16), server_default='team', nullable=False))
    # ### end Alembic commands ###

    # Hand-written: autogenerate detects CHECK constraints only inside
    # create_table, never on an existing one, so the model's __table_args__
    # would have silently diverged from the database.
    op.create_check_constraint(
        'ck_projects_approval_policy', 'projects', "approval_policy IN ('admin','team')"
    )
    # server_default backfills existing rows to 'team'; there is nothing
    # to migrate beyond that, since every project until now behaved as if
    # its single owner decided everything -- which 'team' reproduces
    # exactly for a one-member room.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_projects_approval_policy', 'projects', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'approval_policy')
    op.drop_table('proposal_approvals')
    op.drop_index('ix_proposals_project_id_created_at', table_name='proposals')
    op.drop_table('proposals')
    # ### end Alembic commands ###
