"""add project_jobs

Revision ID: 61ce2ca7e942
Revises: 9a6f721b6f93
Create Date: 2026-08-01 06:06:02.430171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ce2ca7e942'
down_revision: Union[str, Sequence[str], None] = '9a6f721b6f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_jobs',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('ix_project_jobs_project_id', 'project_jobs', ['project_id'], unique=False)

    # Backfill jobs that predate this table, so their artifacts stay
    # reachable once the artifact guard starts requiring a room. Both
    # sources are derivable from the payload the job was submitted with:
    #
    #   - edit jobs carry _conversation_id (Phase 6's stamp), which
    #     resolves to a project via conversations.project_id
    #   - analysis jobs carry video_id, which resolves via videos.project_id
    #
    # submitted_by_user_id falls back to the project's owner: the real
    # submitter was never recorded before now, and the owner is both the
    # likeliest answer and a safe one -- job ownership only grants
    # cancellation (Phase 9b), which the owner should have anyway.
    #
    # A job matching neither shape is left unmapped. Those are raw POST
    # /jobs submissions, which are product-internal with two server-side
    # call sites and belong to no room by design.
    op.execute(
        sa.text(
            """
            INSERT INTO project_jobs (job_id, project_id, submitted_by_user_id, created_at)
            SELECT j.id, c.project_id, p.owner_id, j.created_at
            FROM jobs j
            JOIN conversations c
              ON c.id = (j.payload ->> '_conversation_id')::uuid
            JOIN projects p ON p.id = c.project_id
            WHERE j.payload ? '_conversation_id'
            ON CONFLICT (job_id) DO NOTHING
            """
        )
    )
    op.execute(
        sa.text(
            """
            INSERT INTO project_jobs (job_id, project_id, submitted_by_user_id, created_at)
            SELECT j.id, v.project_id, p.owner_id, j.created_at
            FROM jobs j
            JOIN videos v ON v.id = (j.payload ->> 'video_id')::uuid
            JOIN projects p ON p.id = v.project_id
            WHERE j.payload ? 'video_id'
            ON CONFLICT (job_id) DO NOTHING
            """
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_jobs_project_id', table_name='project_jobs')
    op.drop_table('project_jobs')
    # ### end Alembic commands ###
