"""add jobs.artifacts_cleaned_at

Revision ID: 7b7267092e93
Revises: ba8117bb8b8d
Create Date: 2026-07-31 20:41:26.056091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7267092e93'
down_revision: Union[str, Sequence[str], None] = 'ba8117bb8b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('artifacts_cleaned_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'artifacts_cleaned_at')
    # ### end Alembic commands ###
