"""add project_members

Revision ID: 9a6f721b6f93
Revises: 7b7267092e93
Create Date: 2026-07-31 23:08:27.614857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6f721b6f93'
down_revision: Union[str, Sequence[str], None] = '7b7267092e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_index('ix_project_members_user_id', 'project_members', ['user_id'], unique=False)

    # Backfill every existing project's owner as its first member.
    #
    # Not optional housekeeping: the membership guard added alongside this
    # rejects anyone without a project_members row, so without this every
    # project created before Phase 8 becomes unreachable by the person who
    # made it -- a 404 on their own work, with the data still sitting in
    # the database.
    #
    # Idempotent via ON CONFLICT so a partially-applied or re-run
    # migration doesn't fail on rows it already created.
    op.execute(
        sa.text(
            """
            INSERT INTO project_members (project_id, user_id, role, joined_at)
            SELECT id, owner_id, 'owner', COALESCE(created_at, now())
            FROM projects
            ON CONFLICT (project_id, user_id) DO NOTHING
            """
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_members_user_id', table_name='project_members')
    op.drop_table('project_members')
    # ### end Alembic commands ###
