"""add conversations.memory_processed_at

Revision ID: ba8117bb8b8d
Revises: 8ccc76a18ae4
Create Date: 2026-07-31 16:45:54.462311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8117bb8b8d'
down_revision: Union[str, Sequence[str], None] = '8ccc76a18ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('memory_processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'memory_processed_at')
    # ### end Alembic commands ###
